# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

fastlane_require '../scripts/updateCoreBranch.rb.rb'

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :update_core_branch do |values|
    UI.message values
    countryBranch = values[:countryBranch]
    coreBranch = values[:coreBranch]
    submoduleName = values[:submoduleName]

    return update_submodule(countryBranch, coreBranch, submoduleName)

  end
end
